#!/usr/bin/env bash
#
# Wrapper script to assist in using the release notes script.
#
# Usage:
#   git release-notes start_ref end_ref
#
# Example:
#  git release-notes develop release/2.4.2

. "${BASH_SOURCE%/*}/../$(basename $BASH_SOURCE).sh"
